### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by tsai1993** [k3ho/zim-plugin-cryptselection#1]
i run the command `/usr/bin/gpg2 --always-trust -ear RECIPIENT`, but get the error:

$ /usr/bin/gpg2 --always-trust -ear RECIPIENT
gpg: RECIPIENT: skipped: No public key
gpg: [stdin]: encryption failed: No public key

in meum `Edit-->Crypt selection` there is no change at all.

I'm so sorry to bother you with such a little thing.

**Comment by tsai1993** [comment]
I got it! Thank you for your brilliant plugins!

**Comment by theRealSuperMario** [comment]
Could you share how you did it? I am struggeling, too.
